contributor = "01cc89e1-b7c2-4629-b249-27bb0aec5db3"
# https://github.com/LlmKira/contributor/blob/main/.nerve.toml

language = "English"
issue_auto_label = true
# Whether to automatically label issues
issue_title_format = true
# Whether to use the default issue title format
issue_body_format = true
# Whether to use the default issue body format
issue_close_with_report = true
# Whether to close the issue with a report
